---
# defaults file for provision-ec2-instance
key_pair_name: vyos-build-ami
ec2_region: us-east-1
temp_folder: "{{ playbook_dir }}/files/ssh-keys"
key_pair_file: "{{ temp_folder }}/{{ key_pair_name }}.pem"
instance_type: t3.micro

base_image:
  debian_aws_account_id: "379101102735"
  name: "debian-stretch-hvm-x86_64-*"
  architecture: "x86_64"
  hypervisor: "xen"
  root_device_type: "ebs"

placeholder: vyos-build-ami
volume_size: 4
volume_drive: /dev/nvme1n1
ansible_ssh_private_key_file: "{{ key_pair_file }}"
